# Generated by Django 2.0 on 2017-12-28 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar_Week',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('calendar_week', models.BigIntegerField()),
                ('start_date', models.BigIntegerField()),
                ('end_date', models.BigIntegerField()),
                ('calendar_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Current_Status',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('process_id', models.BigIntegerField()),
                ('project_id', models.BigIntegerField()),
                ('task_id', models.BigIntegerField()),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('user_id', models.BigIntegerField(null=True)),
                ('weekend_id', models.BigIntegerField(null=True)),
                ('duration', models.TimeField(null=True)),
                ('image_data', models.BinaryField(null=True)),
                ('image_thumbnail_data', models.BinaryField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('current_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Current_Status')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DateTimeField(auto_now_add=True)),
                ('current_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Current_Status')),
                ('parent_task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.ProjectTask')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Project', to='Main.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_teamLead', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='Main.Project')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
