# Generated by Django 2.0 on 2017-12-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20171229_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current_status',
            name='status',
        ),
        migrations.AddField(
            model_name='current_status',
            name='status_name',
            field=models.CharField(default='Running', max_length=10),
        ),
    ]
