# Generated by Django 2.0 on 2017-12-29 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20171229_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='current_status',
            old_name='status_name',
            new_name='current_status',
        ),
    ]
